name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run : |
        sudo apt-get update -qq
        sudo apt-get install -y -qq libx11-dev libxtst-dev libxext-dev
    - name: Build
      run: make
    - name: Build .deb package
      run: make deb
    - name: Install .deb packages
      run: sudo dpkg -i deskx*.deb
    - name: Check .deb packages
      run: |
        dpkg-query --status deskx
