name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run : |
        sudo apt-get update -qq
        sudo apt-get install -y -qq libx11-dev libxtst-dev libxext-dev
    - name: Build client
      run: make client
    - name: Build server
      run: make server
    - name: Build client .deb package
      run: make deb-client
    - name: Build server .deb package
      run: make deb-server
    - name: Install .deb packages
      run: sudo dpkg -i deskx-*.deb
    - name: Check .deb packages
      run: |
        dpkg-query --status deskx-client
        dpkg-query --status deskx-server

