name: basic pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run : sudo apt install libx11-dev libxtst-dev libssl-dev
    - name: build client
      run: make client
    - name: build server
      run: make server
